name:   Checkout
on: [push]
jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files Before
              run: ls -a # List all files in the current directory
            - name: Checkout 
              run: | 
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"  # Add remote repository
                git fetch origin
                git checkout main
            - name: List Files After
              run: ls -a