name: Workflow Commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "::error::Missing semicolon"
